#!/bin/sh
#	srl - simple roblox launcher for *nix systems 
#    Copyright (C) 2022 GlitchPhoenix98
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

# thanks to dietnusse for teaching me shell 
_version=0.0.2
_dxvk=1.10.3
_client_url="https://www.roblox.com/download/client"

version() {
    printf "srl v${_version}\n"
}

usage() {
    printf 'Usage: srl [OPTION]...\n'
    printf 'Roblox + Wine setup utility.\n'
    printf '\n'
    printf '  -i, --install  Install Roblox.\n'
    printf '  -v, --version  Displays version.\n'
    printf '  -h, --help     Show usage.\n'
    printf '\n'
}

die() {
    printf "\e[1;37mERROR: \e[0m${@}\n"
    exit 1
}

install() {
	[ "$UID" -eq 0 ] && die 'Cannot install Roblox as root!'
	[ ! -x /usr/bin/wine ] && die 'Wine binary not found or not executable'
	[ ! -x /usr/bin/curl ] && die 'Curl binary not found or not executable'
	[ ! -x /usr/bin/tar ] && die 'Tar binary not found or not executable'
		printf "\e[1;37mDownloading Roblox ...\e[0m\n"
		curl -L ${_client_url} -o /tmp/client || die 'curl failed'
	printf "\e[1;37mDownloading DXVK ...\e[0m\n"
		curl -L https://github.com/doitsujin/dxvk/releases/download/v${_dxvk}/dxvk-${_dxvk}.tar.gz -o /tmp/srl-dxvk.tar.gz || die 'curl failed'
		tar -xvf /tmp/srl-dxvk.tar.gz -C /tmp/ || die 'tar failed'
	printf "\e[1;37mInstalling DXVK ...\e[0m\n"
		sh /tmp/dxvk-${_dxvk}/setup_dxvk.sh install || die 'setup_dxvk.sh failed'
	printf "\e[1;37mInstalling Roblox ...\e[0m\n"
	wine /tmp/client &> /dev/null
	# Remove desktop and lnk files from home folder
	rm -v ${HOME}/Desktop/{'Roblox Player.desktop','Roblox Player.lnk','Roblox Studio.desktop','Roblox Studio.lnk'}
}

rblxplay() {
	printf "\e[1;37mPlease do not manually launch this, use the browser.\e[0m\n"
	cd $WINEPREFIX
	wine [ -f "$robloxverdir"/version-*/RobloxPlayerLauncher.exe ]
}

case "$1" in
    -i) install;;
    -v) version;;
    -h) usage;;
    --install) install;;
    --version) version;;
    --help) usage;;
    --rblxplay) rblxplay;;
    *) usage; exit 1;;
esac
